version: '3.8'
services:
  web:
    build: ./
    # constainer_name: Ayush's_Portfolio
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true



