name: Deploy to EC2

on:
  push:
    branches:
      - main  # Change this to your main branch name if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        run: |
          docker build -t my-portfolio .
          docker tag my-portfolio ${{ secrets.DOCKER_USERNAME }}/my-portfolio:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-portfolio:latest

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user  # Assuming the default user for Amazon Linux
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/my-portfolio:latest
            if docker ps -a | grep -q my-portfolio; then
              docker stop my-portfolio
              docker rm my-portfolio
            fi
            docker run -d -p 5173:5173 --name my-portfolio ${{ secrets.DOCKER_USERNAME }}/my-portfolio:latest
